# Generated by Django 3.1.7 on 2021-02-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EndOf', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
